version = 1

[[annotations]]
path = ["mix.exs", "lib/**", "test/**", "README.md"]
SPDX-FileCopyrightText = "2024 Ryota Kinukawa"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "mix.lock",
  ".formatter.exs",
  ".tool-versions",
  ".gitignore",
  ".github/**",
  "REUSE.toml",
]
SPDX-FileCopyrightText = "2024 Ryota Kinukawa"
SPDX-License-Identifier = "CC0-1.0"
