version = 1

[[annotations]]
path = [
  "README.md",
  "lib/**",
  "mix.exs",
  "test/**",
]
SPDX-FileCopyrightText = "2024 Ryota Kinukawa"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  ".credo.exs",
  ".formatter.exs",
  ".fwatch.exs",
  ".fwatch.sh",
  ".github/**",
  ".gitignore",
  "REUSE.toml",
  "config/**",
  "mise.toml",
  "mix.lock",
]
SPDX-FileCopyrightText = "2024 Ryota Kinukawa"
SPDX-License-Identifier = "CC0-1.0"
